strictness: veryhigh
test-warnings: true
output-format: pylint

uses:
  - django

ignore-paths:
  - .mypy_cache
  - media
  - migrations
  - node_modules
  - venv
  - __pycache__
  - manage.py
  - docs

mypy:
  run: true

bandit:
  run: true

dodgy:
  run: false

pylint:
  enable:
    - useless-suppression
  options:
    max-line-length: 119
    good-names: pk,e,f
    max-parents: 12

pep8:
  disable:
    - N815
  options:
    max-line-length: 119