strictness: veryhigh
test-warnings: true

uses:
  - django

ignore-paths:
  - .mypy_cache
  - media
  - migrations
  - node_modules
  - venv
  - __pycache__
  - manage.py

mypy:
  run: true

bandit:
  run: true

dodgy:
  run: false

pylint:
  enable:
    - useless-suppression
  options:
    max-line-length: 119
    good-names: pk
    max-parents: 12

pep8:
  options:
    max-line-length: 119