version: "3.9"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static-root:/var/www/html/static:ro
      - media-root:/var/www/html/media:ro
    ports:
      - 8080:80
    restart: always
    networks:
      - radiodns
    depends_on:
      - artemis
  radiodns:
    build: .
    hostname: radiodns
    environment:
      - STATIC_ROOT=/var/www/html/static
      - MEDIA_ROOT=/var/www/html/media
      - PROXY=${PROXY}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - STOMP_USERNAME=${ARTEMIS_USERNAME}
      - STOMP_PASSWORD=${ARTEMIS_PASSWORD}
    volumes:
      - ./db:/usr/src/app/db
      - static-root:/var/www/html/static
      - media-root:/var/www/html/media
    image: radiodns
    restart: always
    networks:
      - radiodns
  artemis:
    image: "artemis-adoptopenjdk-11:latest"
    hostname: artemis
    ports:
      - "61613:61613"
      - "8161:8161"
    volumes:
      - ./artemis-instance:/var/lib/artemis-instance
    environment:
      - ARTEMIS_USER=${ARTEMIS_USERNAME}
      - ARTEMIS_PASSWORD=${ARTEMIS_PASSWORD}
      - ANONYMOUS_LOGIN=true
    networks:
      - radiodns
    restart: always
networks:
  radiodns:
volumes:
  static-root:
  media-root: