# Generated by Django 3.1.6 on 2021-02-15 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=8)),
                ('medium_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Bearer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bearer_id', models.TextField()),
                ('cost', models.IntegerField()),
                ('mimeValue', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioepg.service')),
            ],
        ),
    ]
