# Generated by Django 3.1.6 on 2021-02-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioepg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearer',
            name='mimeValue',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
