# Generated by Django 3.1.6 on 2021-02-15 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radioepg', '0002_auto_20210215_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearer',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bearers', to='radioepg.service'),
        ),
    ]
