# Generated by Django 3.1.6 on 2021-02-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioepg', '0003_auto_20210215_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='fqdn',
            field=models.CharField(default='radiodns.ltn.fi', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='service',
            name='service_identifier',
            field=models.CharField(default='radiodns', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
