# Generated by Django 3.1.6 on 2021-02-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioepg', '0004_auto_20210219_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bearer',
            old_name='mimeValue',
            new_name='mime_value',
        ),
    ]
