# Generated by Django 3.1.6 on 2021-02-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioepg', '0005_auto_20210219_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
    ]
