# Generated by Django 3.1.6 on 2021-02-22 10:54

from django.db import migrations, models
import radioepg.storage


class Migration(migrations.Migration):

    dependencies = [
        ('radioepg', '0006_service_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.ImageField(null=True, storage=radioepg.storage.OverwriteStorage(), upload_to='media/logos/'),
        ),
    ]
