# Generated by Django 3.1.7 on 2021-02-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioepg', '0009_auto_20210222_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearer',
            name='bearer_id',
            field=models.TextField(unique=True),
        ),
    ]
