# Generated by Django 3.1.7 on 2021-03-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioepg', '0011_imageslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslide',
            name='url',
            field=models.ImageField(upload_to='slides/'),
        ),
    ]
