# Generated by Django 3.1.7 on 2021-03-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioepg', '0014_auto_20210310_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageSlide',
        ),
    ]
