# Generated by Django 3.1.7 on 2021-03-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioepg', '0016_auto_20210323_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearer',
            name='frequency',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
