# Generated by Django 3.2 on 2021-04-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioepg', '0020_auto_20210407_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='logo',
        ),
    ]
