# Generated by Django 3.2.1 on 2021-05-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioepg', '0022_service_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='logo112',
            field=models.ImageField(editable=False, null=True, upload_to='resized_logos/'),
        ),
        migrations.AddField(
            model_name='service',
            name='logo128',
            field=models.ImageField(editable=False, null=True, upload_to='resized_logos/'),
        ),
        migrations.AddField(
            model_name='service',
            name='logo32',
            field=models.ImageField(editable=False, null=True, upload_to='resized_logos/'),
        ),
        migrations.AddField(
            model_name='service',
            name='logo320',
            field=models.ImageField(editable=False, null=True, upload_to='resized_logos/'),
        ),
        migrations.AddField(
            model_name='service',
            name='logo600',
            field=models.ImageField(editable=False, null=True, upload_to='resized_logos/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviceIdentifier',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
