# Generated by Django 3.1.7 on 2021-03-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radiovis', '0002_imageslide_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slides/')),
            ],
        ),
        migrations.CreateModel(
            name='TextSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=128)),
                ('sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='imageslide',
            name='link',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='imageslide',
            name='sent',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imageslide',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiovis.image'),
        ),
    ]
