# Generated by Django 3.1.7 on 2021-04-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiovis', '0003_auto_20210330_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslide',
            name='sent',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='textslide',
            name='sent',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
