# Generated by Django 3.2 on 2021-04-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiovis', '0006_auto_20210414_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image112',
            field=models.ImageField(upload_to='autoscaled/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image128',
            field=models.ImageField(upload_to='autoscaled/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image32',
            field=models.ImageField(upload_to='autoscaled/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image320',
            field=models.ImageField(upload_to='autoscaled/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image600',
            field=models.ImageField(upload_to='autoscaled/'),
        ),
        migrations.AlterField(
            model_name='textslide',
            name='message',
            field=models.CharField(default='', max_length=128),
        ),
    ]
