# Generated by Django 3.2 on 2021-04-27 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radiovis', '0008_alter_imageslide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslide',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiovis.image'),
        ),
    ]
