# Generated by Django 3.2.1 on 2021-05-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiovis', '0009_alter_imageslide_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image112',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image128',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image32',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image320',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image600',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
