# Generated by Django 3.2.2 on 2021-05-07 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radiovis', '0010_auto_20210505_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslide',
            name='image',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='radiovis.image'),
        ),
        migrations.AlterField(
            model_name='imageslide',
            name='link',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='imageslide',
            name='trigger_time',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='textslide',
            name='message',
            field=models.CharField(default='', editable=False, max_length=128),
        ),
    ]
