# Generated by Django 3.2.2 on 2021-05-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radiovis', '0011_auto_20210507_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslide',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiovis.image'),
        ),
        migrations.AlterField(
            model_name='imageslide',
            name='link',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='imageslide',
            name='trigger_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='textslide',
            name='message',
            field=models.CharField(default='', max_length=128),
        ),
    ]
